---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-debug
  namespace: flux-system
spec:
  interval: 31s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/homelab/debug
  prune: true
  wait: true
  timeout: 5m0s

