---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 31s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./secrets/homelab/secrets
  prune: true
  wait: true
  timeout: 5m0s

