---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: woodpecker
  namespace: woodpecker
spec:
  type: oci
  interval: 5m
  url: oci://ghcr.io/woodpecker-ci/helm
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: woodpecker
  namespace: woodpecker
spec:
  interval: 5m
  chart:
    spec:
      chart: woodpecker
      sourceRef:
        kind: HelmRepository
        name: woodpecker
        namespace: woodpecker
      version: "3.1.1"
