apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: production
spec:
  interval: 10m
  chart:
    spec:
      chart: gitlab
      version: 9.0.0
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
  values:
    global:
      edition: ce
      hosts:
        domain: towelie.dev
      ingress:
        configureCertmanager: false
        class: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
    gitlab:
      webservice:
        replicas: 1
      gitaly:
        replicas: 1
    registry:
      enabled: false
    minio:
      enabled: false
    gitlab-runner:
      install: true

