apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: production
spec:
  interval: 10m
  chart:
    spec:
      chart: gitlab
      version: 8.0.0
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
  values:
    global:
      edition: ce
      hosts:
        domain: towelie.dev
      certmanager-issuer:
        email: mail@towelie.dev

