---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 1h
  url: https://charts.gitlab.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  releaseName: gitlab
  chart:
    spec:
      chart: gitlab
      version: 9.0.0
      sourceRef:
        kind: HelmRepository
        name: gitlab
  interval: 5m0s
