apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: drone-cert
  namespace: drone
spec:
  secretName: drone-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - drone.towelie.dev

