apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: drone
  namespace: drone
spec:
  releaseName: drone
  chart:
    spec:
      chart: drone
      version: 0.6.5
      sourceRef:
        kind: HelmRepository
        name: drone
  interval: 5m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/drone/charts/blob/master/charts/drone/values.yaml

