apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: production
spec:
  interval: 5m0s
  releaseName: harbor
  chart:
    spec:
      chart: harbor
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  values:
    externalURL: https://harbor.towelie.dev
    expose:
      type: ingress
      ingress:
        enabled: true
        hosts:
          core: harbor.towelie.dev
          notary: notary.towelie.dev
          chartmuseum: chartmuseum.towelie.dev
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: web
        ingressClass: traefik
        tls:
          enabled: false
    harborAdminPassword: "YNqP7kkR3Hcf82"


