apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tekton
  namespace: tekton-pipelines
spec:
  interval: 5m
  chart:
    spec:
      chart: tekton-pipelines
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: tekton-charts
        namespace: flux-system
  values:
    dashboard:
      enabled: true
      ingress:
        enable: true
        hosts:
          - tekton.towelie.dev
        annotations:
          kubernetes.io/ingress.class: "traefic"
