apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: tekton-charts
  namespace: flux-system
spec:
  url: https://cdfoundation.github.io/tekton-helm-chart
  interval: 1h
