apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tekton
  namespace: tekton-pipelines
spec:
  interval: 5m
  chart:
    spec:
      chart: tekton-pipeline
      version: 1.0.5
      sourceRef:
        kind: HelmRepository
        name: tekton-charts
        namespace: flux-system
