apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - ./dashboard/
