apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  interval: 50m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: kube-system
      version: "35.2.0"
  values:
    ports:
      traefik:
        expose: true
    api:
      dashboard: true
    ingressRoute:
      dashboard:
        enabled: true

