apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  releaseName: harbor
  chart:
    spec:
      chart: harbor
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: harbor
  interval: 5m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/goharbor/harbor-helm/blob/main/values.yaml
  values:
    externalURL: ""
    expose:
      type: ingress
      ingress:
        enabled: true
        hosts:
          core: harbor.your_domain.com
          notary: notary.your_domain.com
          chartmuseum: chartmuseum.your_domain.com
        annotations:
          ingress.kubernetes.io/ssl-redirect: false
          traefik.ingress.kubernetes.io/router.entrypoints: web
          ingress.kubernetes.io/proxy-body-size: 1Gi
          nginx.ingress.kubernetes.io/proxy-body-size: 1Gi
        ingressClass: traefik
        tls:
          enabled: false
    harborAdminPassword: "Harbor12345"


