apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
- environments.yaml
