apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard
  namespace: ingress
spec:
  secretName: wildcard-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  commonName: "*.towelie.dev"
  dnsNames:
  - "*.towelie.dev"
  - "towelie.dev"
  duration: 2160h # 90d
  renewBefore: 360h # 15d

