apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: kube-system
spec:
  template:
    spec:
      volumes:
        - name: custom-coredns-config
          configMap:
            name: coredns-hosts-override
      containers:
        - name: coredns
          volumeMounts:
            - name: custom-coredns-config
              mountPath: /etc/coredns/custom

