apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: darts
  namespace: darts
spec:
  interval: 5m0s
  releaseName: darts
  chart:
    spec:
      chart: darts
      version: "0.1.0"
      chartRef:
        kind: OCIRepository
        name: darts
        namespace: darts
  # Default values
  # TODO: Add Link
  values:
    imagePullSecrets:
      - name: harbor-credentials
    image:
      tag: "1.0.0"
    ingress:
      enabled: true
      className: traefik
      annotations:
        - kubernetes.io/ingress.class: traefik
        - traefik.ingress.kubernetes.io/router.entrypoints: websecure
        - kubernetes.io/tls-acme: "true"
      hosts:
        - host: darts.towelie.dev
          paths:
            - path: /
              pathType: ImplementationSpecific
    tls:
      - hosts:
          - "darts.towelie.dev"
        secretName: darts-tls
