apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  releaseName: gitlab
  chart:
    spec:
      chart: gitlab
      version: 9.0.0
      sourceRef:
        kind: HelmRepository
        name: gitlab
  interval: 5m0s
  values:
    global:
      edition: ce
      hosts:
        domain: gitlab.towelie.dev
        externalIP: 91.4.94.120
      ingress:
        provider: traefik
        annotations: 
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          kubernetes.io/ingress.class: "traefik"
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
        tls:
          enabled: true
          secretName: gitlab-cert

