apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  releaseName: gitlab
  chart:
    spec:
      chart: gitlab
      version: 9.0.0
      sourceRef:
        kind: HelmRepository
        name: gitlab
  interval: 5m0s
  values:
    global:
      hosts:
        domain: towelie.dev
      ingress:
        class: traefik                   
        configureCertmanager: false
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
        tls:
          enabled: true
      edition: ce

    nginx-ingress:
      enabled: false                   

    certmanager:
      install: false                   

