apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  releaseName: gitlab
  chart:
    spec:
      chart: gitlab
      version: 9.0.0
      sourceRef:
        kind: HelmRepository
        name: gitlab
  interval: 5m0s
  values:
    global:
      edition: ce
      hosts:
        domain: towelie.dev
      initialRootPassword:
        secret: gitlab-initial-root-password
        key: password
      traefik:
        install: true
        ports:
          gitlab-shell:
            expose: true
            port: 2222
            exposedPort: 22
      ingress:
        class: traefik                   
        configureCertmanager: true
        tls:
          enabled: true
      kas:
        enabled: false                   

    prometheus:
      install: false                   

    nginx-ingress:
      enabled: false                   

    certmanager:
      install: false                   

    certmanager-issuer:
      email: mail@towelie.dev

    traefik:
      install: true
      ports:
        gitlab-shell:
          expose: true
          port: 2222
          exposedPort: 22


