apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  chart:
    spec:
      version: ">=1.0.0"
  values:
    externalURL: "https://harbor.towelie.dev"
    harborAdminPassword: "Harbor123456"
    expose:
      type: ingress
      tls:
        enabled: true
        certSource: secret
        secret:
          secretName: harbor-tls
      ingress:
        enabled: true
        className: traefik
        hosts:
          core: harbor.towelie.dev
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure

