apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  chart:
    spec:
      version: ">=1.0.0"
  values:
    externalURL: "https://harbor.towelie.dev"
    harborAdminPassword: "Harbor123456"
    expose:
      ingress:
        enabled: true
        hosts:
          core: harbor.towelie.dev
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        tls:
          enabled: true
          secretName: harbor-tls

