apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich
  namespace: flux-system
spec:
  chart:
    spec:
      version: 0.9.3
  values:
    useDeprecatedPostgresChart: true

    immich:
      persistence:
        library:
          existingClaim: "immich-data"

    server:
      enabled: true
      image:
        repository: ghcr.io/immich-app/immich-server
        pullPolicy: IfNotPresent
      ingress:
        main:
          enabled: true
          ingressClassName: "traefik"
          annotations:
            # proxy-body-size is set to 0 to remove the body limit on file uploads
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            kubernetes.io/ingress.class: "traefik"
            kubernetes.io/tls-acme: "true"
            cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
          hosts:
            - host: immich.towelie.dev
              paths:
                - path: "/"
          tls:
            - secretName: immich-tls
              hosts:
                - immich.towelie.dev

    redis:
      enabled: true
      architecture: standalone
      auth:
        enabled: false

    postgresql:
      enabled: true
      image:
        repository: tensorchord/pgvecto-rs
        tag: pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
      global:
        postgresql:
          auth:
            username: immich
            database: immich
            password: immich
      primary:
        containerSecurityContext:
          readOnlyRootFilesystem: false
        initdb:
          scripts:
            create-extensions.sql: |
              CREATE EXTENSION cube;
              CREATE EXTENSION earthdistance;
              CREATE EXTENSION vectors;
