apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich
  namespace: flux-system
spec:
  chart:
    spec:
      version: 0.9.3
  values:
    immich:
      persistence:
        library:
          existingClaim: "immich-data"

