apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/longhorn
  - ../base/gitlab
patches:
  - path: longhorn-values.yaml
    target:
      kind: HelmRelease
      namespace: longhorn-system
  - path: gitlab-values.yaml
    target:
      kind: HelmRelease
      namespace: gitlab
