apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/harbor
  - ../base/darts
patches:
  - path: darts-values.yaml
    target:
      kind: HelmRelease
      namespace: darts
  - path: harbor-values.yaml
    target:
      kind: HelmRelease
      namespace: harbor
