apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/harbor
  - ../base/longhorn
patches:
  - path: harbor-values.yaml
    target:
      kind: HelmRelease
      namespace: harbor
  - path: longhorn-values.yaml
    target:
      kind: HelmRelease
      namespace: longhorn-system
