apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn-system
  namespace: longhorn-system
spec:
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      version: 1.8.1
      sourceRef:
        kind: HelmRepository
        name: longhorn-system
  interval: 5m0s
  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 1
    ingress:
      enabled: true
      ingressClassName: "traefik"
      host: longhorn.towelie.dev
      tls: true
      secureBackends: true
      tlsSecret: longhorn-cert
      path: /
      pathType: ImplementationSpecific
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        kubernetes.io/ingress.class: "traefik"
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
