apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: ">=1.0.0"
  # Default values
  # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
  values:
    ingress:
      className: traefik
      hosts:
        - host: podinfo.towelie.dev
          paths:
            - path: /
              pathType: ImplementationSpecific

