apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart:
    spec:
      version: ">=1.0.0"
  # Default values
  # https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
  values:
