apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
spec:
  chart:
    spec:
      version: 1.17.0
  values:
    externalURL: "https://harbor.towelie.dev"
    expose:
      ingress:
        hosts:
          core: harbor.towelie.dev
    harborAdminPassword: "Harbor123456"



