apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: nextjs-build-pipeline
  namespace: tekton-pipelines
spec:
  params:
    - name: IMAGE
    - name: GIT_URL
    - name: GIT_REVISION
  tasks:
    - name: build-and-push
      taskRef:
        name: build-and-push-nextjs
      params:
        - name: IMAGE
          value: $(params.IMAGE)
        - name: GIT_URL
          value: $(params.GIT_URL)
        - name: GIT_REVISION
          value: $(params.GIT_REVISION)
