apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push-nextjs
  namespace: tekton-pipelines
spec:
  params:
    - name: IMAGE
      type: string
    - name: GIT_URL
      type: string
    - name: GIT_REVISION
      type: string
  steps:
    - name: git-clone
      image: alpine/git
      script: |
        git clone $(params.GIT_URL) /workspace/src
        cd /workspace/src
        git checkout $(params.GIT_REVISION)

    - name: build-and-push
      image: quay.io/podman/stable
      securityContext:
        privileged: true
      script: |
        cd /workspace/src
        podman login --username admin --password YNqP7kkR3Hcf82 --tls-verify=false harbor-registry.production.svc.cluster.local:5000
        podman build -t $(params.IMAGE) .
        podman push --tls-verify=false $(params.IMAGE)
