apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
namespace: flux-system
metadata:
  name: immich
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/immich-app/immich-charts
  type: oci
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
namespace: flux-system
metadata:
  name: immich
  namespace: flux-system
spec:
  install:
    disableWait: true
  upgrade:
    disableWait: true
  releaseName: immich
  interval: 5m0s
  timeout: 0m30s
  chart:
    spec:
      chart: immich
      version: 0.9.2
      sourceRef:
        kind: HelmRepository
        name: immich
