kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich-data
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
  storageClassName: longhorn
